Feature #33 - show archived bundles
codiak/socialarchive-dapp pull request #55
Opened 2022-02-08 08:15 UTC by ameer-clara

2022-02-09 13:09 UTC, kirlen requested changes
freakin' awesome, ameer!

2022-02-09 13:45 UTC, ameer-clara commented on client/src/utils/store.js
> +    let feeds = await b.getFeeds(feedIndex, 5);
Good catch! Should come from front end. Will update GET_FEEDS_FROM_SWARM dispatch and browse page to support it. After this merge, we should support pagination and some sort of cache as @codiak mentioned in our call.

2022-02-09 13:46 UTC, ameer-clara commented on client/src/process/Beejs.tsx
> +    return buildAxiosFetch(axiosInstance);
Thanks, much cleaner, noted.

2022-02-12 12:43 UTC, kirlen commented
@ameer-clara, since you keep tweaking (improving!) this branch, had to join in the fun by displaying the archive date in there. hope you don't mind!

2022-02-12 12:44 UTC, kirlen commented on client/src/process/Beejs.tsx
> +    return buildAxiosFetch(axiosInstance);
👍

2022-02-13 07:42 UTC, kirlen approved these changes
When loading feeds from cache, UI still says "Downloading", and takes longer than I'd expect -- but approving PR because clearly you will keep tweaking until it's merged ;-) !!!

2022-02-14 04:24 UTC, ameer-clara commented
> When loading feeds from cache, UI still says "Downloading", and takes longer than I'd expect -- but approving PR because clearly you will keep tweaking until it's merged ;-) !!!

Thanks!!!! Updated #62 with sequence diagrams to show caching and implemented an improvement.

2022-02-14 04:25 UTC, merged